### ISSUE TITLE
[Bug] ConfigMap/Secrets中的行首空格未正常展示

### ISSUE THREAD

**Issue by AutumnSun1996** [1Panel-dev/KubePi#196]
**KubePi 版本**
v1.7.0

**Kubernetes 版本**
-

**Bug 描述**
在ConfigMap/Secrets中, 无法正常展示yaml的行首空格

**Bug 重现步骤(有截图更好)**
创建configMap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-demo
  namespace: default
data:
  config.yml: |
    log:
      level: INFO
    users:
      - name: user1
        password: password1
      - name: user2
        password: password2
```

展示效果为:
![image](https://github.com/1Panel-dev/KubePi/assets/20429502/7a0f3b29-7d54-4d23-87a8-4c518f8b8ff5)
