### ISSUE TITLE
[Bug] 在本地 k3s 集群中安装 KubePi 之后，重启集群后，KubePi 中的数据会全部丢失

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/KubePi#197]
**KubePi 版本**
 1.7.0

**Kubernetes 版本**
 v1.27.4+orb1 [使用 orbstack 1.5.0 (16842) 创建的集群]

**Bug 描述**
 在本地 k3s 集群中安装 KubePi 之后，重启集群后，KubePi 中的数据会全部丢失

安装命令
```
kubectl create deployment kubepi --image 1panel/kubepi
kubectl expose deploy/kubepi --type=ClusterIP --port=80
```
使用 kukeconfig 文件方式导入集群，将 `~/.kube/config` 文件中的 `server` 的值改为 `https://kubernetes.default.svc`

**Comment by shaxiaozz** [comment]
@mx2913 kubepi 集群相关数据是存放到/var/lib/kubepi/db路径下的。如果你是K8s部署的kubepi，那你可以给deployment外挂个PVC。如下：
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kubepi
    release: v1.7.0
  name: kubepi-db-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepi
  labels:
    name: kubepi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubepi
  #设置滚动更新策略
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kubepi
    spec:
      containers:
      - name: kubepi
        image: 1panel/kubepi:v1.7.0
        imagePullPolicy: IfNotPresent
        #设置容器端口
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        #容器路径挂载
        volumeMounts:
        - mountPath: /etc/localtime
          name: time
          readOnly: true
        - name: kubepi-db-pvc
          mountPath: /var/lib/kubepi/db
      volumes:
      - name: time
        hostPath:
          path: /etc/localtime
      - name: kubepi-db-pvc
        persistentVolumeClaim:
          claimName: kubepi-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kubepi-svc
  labels:
    name: kubepi
spec:
  selector:
    name: kubepi
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
```

![image](https://github.com/1Panel-dev/KubePi/assets/43721571/773de7b4-21d8-4104-8be5-6d4e47c39a11)

**Comment by mx2913** [comment]
十分感谢，问题按照提供的方法已经解决了，不过由于 `k8s` 集群是由 `OrbStack` 创建的，`storageClass` 是 `local-path` 所以对 yaml 文件进行了修改
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubepi-db-pvc
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeMode: Filesystem
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepi
  labels:
    name: kubepi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubepi
  #设置滚动更新策略
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kubepi
    spec:
      containers:
        - name: kubepi
          image: 1panel/kubepi:v1.7.0
          imagePullPolicy: IfNotPresent
          #设置容器端口
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          #容器路径挂载
          volumeMounts:
            - mountPath: /etc/localtime
              name: time
              readOnly: true
            - name: kubepi-db-pvc
              mountPath: /var/lib/kubepi/db
      volumes:
        - name: time
          hostPath:
            path: /etc/localtime
        - name: kubepi-db-pvc
          persistentVolumeClaim:
            claimName: kubepi-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kubepi-svc
  labels:
    name: kubepi
spec:
  selector:
    name: kubepi
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
```

现在已经可以随意开启关闭集群都能保留数据了

![图片](https://github.com/1Panel-dev/KubePi/assets/15864713/58149c08-95b5-4e9f-bd1d-0086d649358b)
